const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 600;

const GAME_STARTING_X = 200;
const GAME_STARTING_Y = 0;
const GAME_WIDTH = 400;
const GAME_HEIGHT = 800;
const GAME_WIDTH_BLOCKS = 10;
const GAME_HEIGHT_BLOCKS = 15;
const GAME_BLOCK_SIZE = 40;

const BLUE_BLOCK_LOCATION = "images/Blue block.png";
const RED_BLOCK_LOCATION = "images/Red block.png";
const GREEN_BLOCK_LOCATION = "images/Green block.png";
const ORANGE_BLOCK_LOCATION = "images/Orange block.png";
const TEAL_BLOCK_LOCATION = "images/Teal block.png";
const GRAY_BLOCK_LOCATION = "images/Gray block.png";
const YELLOW_BLOCK_LOCATION = "images/Yellow block.png";
const PINK_BLOCK_LOCATION = "images/Pink block.png";
const STATIONARY_BLOCK_LOCATION = "images/Gray block.png";
const BUTTON_LOCATION = "images/Button.png";

const MENU_BACKGROUND_COLOUR = '#222222';
const LOGO_COLOUR = '#dddddd';
const BUTTON_COLOUR = '#dddddd';
const BLOCK_BORDER_COLOUR = '#000000';
const GAME_GRID_COLOUR = '#ffffff';
const GAME_BACKGROUND_COLOUR = '#444444';
const ABILITY_BACKGROUND_COLOUR = 'rgb(68, 68, 68)';
const ABILITY_FOREGROUND_COLOUR = 'rgba(0, 0, 0, 0.5)';
const ABILITY_TEXT_COLOUR = '#ffffff';
const SCORE_COLOUR = '#333333';
const SCORE_LABEL_COLOUR = '#333333';

const MAX_FIGURES = 7;
const BLOCK_BORDER_WIDTH = 2;
const EMPTY_CELL = 0;

const LINE_DESTROYER_ANIMATION_TIME_FOR_ROW = 0.3;
const LINE_DESTROYER_COOLDOWN = 60;

const FIRST_ABILITY_X_POSITION = 50;
const FIRST_ABILITY_Y_POSITION = 50;
const ABILITY_TEXT_X_POSITION = 100;
const ABILITY_TEXT_Y_POSITION = 90;
const ABILITY_WIDTH = 100;
const ABILITY_HEIGHT = 100;
const HIGH_SCORE_LABEL_X_POSITION = 700;
const HIGH_SCORE_LABEL_Y_POSITION = 40;
const HIGH_SCORE_X_POSITION = 700;
const HIGH_SCORE_Y_POSITION = 60;
const SCORE_LABEL_X_POSITION = 700;
const SCORE_LABEL_Y_POSITION = 100;
const SCORE_X_POSITION = 700;
const SCORE_Y_POSITION = 120;

const LOGO_TEXT_FONT = "200px Georgia";
const MENU_BUTTON_TEXT_FONT = "30px Georgia";
const GAME_BUTTON_TEXT_FONT = "40px Georgia";
const ABILITY_TEXT_FONT = "120px Georgia";
const SCORE_FONT = "20px Georgia";
const SCORE_LABEL_FONT = "30px Georgia";

const LOGO_X_POSITION = 400;
const LOGO_Y_POSITION = 100;
const NORMAL_GAME_BUTTON_STARTING_X_POSITION = 250;
const NORMAL_GAME_BUTTON_STARTING_Y_POSITION = 250;
const CHALLENGE_GAME_BUTTON_STARTING_X_POSITION = 250;
const CHALLENGE_GAME_BUTTON_STARTING_Y_POSITION = 375;

const MENU_BUTTON_STARTING_X_POSITION = 625;
const MENU_BUTTON_STARTING_Y_POSITION = 525;
const NORMAL_GAME_BUTTON_SIZE = 1;
const CHALLENGE_GAME_BUTTON_SIZE = 1;
const MENU_BUTTON_SIZE = 0.5;

const SCORE_LABEL_TEXT = "SCORE";
const HIGH_SCORE_LABEL_TEXT = "HIGH SCORE";

const CHALLENGE_ROWS = 4;
const MAX_NUMBER_OF_CHALLENGE_BLOCKS_PER_ROW = 9;

const NEXT_FIGURE_STARTING_X_POSITION = 50;
const NEXT_FIGURE_STARTING_Y_POSITION = 300;
const NEXT_FIGURE_WIDTH = ABILITY_WIDTH;
const NEXT_FIGURE_HEIGHT = ABILITY_HEIGHT;

//global variables
